server:
  debug: false
  listenAddr: ":8080"
  jwtSecret: default-secret-key
  # proxyHeaderName: X-Username
  rootDirectory: storage/

agent:
  # model: your-model
  # baseUrl: https://ai.rehiy.wang/v1
  # apiKey: your-api-key

apisix:
  # adminUrl: http://127.0.0.1:9180
  # adminKey: your-admin-key

docker:
  # host: unix:///var/run/docker.sock
  # host: tcp://127.0.0.1:2375
  containerRoot: container/
  registries:
     # - name: Company Hub
     #   description: 公司内部镜像仓库
     #   url: hub.example.com
     #   username: debug
     #   password: 123

marketplace:
  baseUrl: https://appstore.rehi.org

members:
  - username: admin
    password: admin
    homeDirectory: .
    allowTerminal: true

  - username: user1
    password: password1
    homeDirectory: user1/
    allowTerminal: false

  - username: user2
    password: password2
    homeDirectory: user2/
    allowTerminal: false
