server:
  debug: false
  listenAddr: ":8080"
  jwtSecret: default-secret-key
  # proxyHeaderName: X-Username
  rootDirectory: storage/

docker:
  # host: unix:///var/run/docker.sock
  # host: tcp://127.0.0.1:2375
  containerRoot: container/
  registries:
     # - name: CSIG Hub
     #   description: 公司内部镜像仓库
     #   url: hub.example.com
     #   username: debug
     #   password: 123

apisix:
  # adminUrl: http://127.0.0.1:9180
  # adminKey: your-admin-key

members:
  - username: admin
    password: admin
    homeDirectory: .
    allowTerminal: true

  - username: user1
    password: password1
    homeDirectory: user1/
    allowTerminal: false

  - username: user2
    password: password2
    homeDirectory: user2/
    allowTerminal: false
