package helper

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	yaml "gopkg.in/yaml.v3"
)

// ComposeService 定义 docker-compose service 配置
type ComposeService struct {
	Image       string            `yaml:"image"`
	ContainerName string          `yaml:"container_name,omitempty"`
	Environment []string          `yaml:"environment,omitempty"`
	Ports       []string          `yaml:"ports,omitempty"`
	Volumes     []string          `yaml:"volumes,omitempty"`
	NetworkMode string            `yaml:"network_mode,omitempty"`
	Restart     string            `yaml:"restart,omitempty"`
	Command     string            `yaml:"command,omitempty"`
	WorkingDir  string            `yaml:"working_dir,omitempty"`
	User        string            `yaml:"user,omitempty"`
	Hostname    string            `yaml:"hostname,omitempty"`
	Deploy      *ComposeDeploy    `yaml:"deploy,omitempty"`
	Labels      map[string]string `yaml:"labels,omitempty"`
}

// ComposeDeploy 定义资源限制配置
type ComposeDeploy struct {
	Resources *ComposeResources `yaml:"resources,omitempty"`
}

// ComposeResources 定义资源配置
type ComposeResources struct {
	Limits *ComposeLimit `yaml:"limits,omitempty"`
}

// ComposeLimit 定义资源限制
type ComposeLimit struct {
	Cpus   string `yaml:"cpus,omitempty"`
	Memory string `yaml:"memory,omitempty"`
}

// ComposeFile 定义 docker-compose 文件结构
type ComposeFile struct {
	Version  string                 `yaml:"version"`
	Services map[string]ComposeService `yaml:"services"`
}

// CreateComposeFile 创建 compose 配置文件
func CreateComposeFile(containerRoot, containerName string, service ComposeService) error {
	if containerRoot == "" || containerName == "" {
		return nil
	}

	containerDir := filepath.Join(containerRoot, containerName)
	if err := os.MkdirAll(containerDir, 0755); err != nil {
		return fmt.Errorf("创建容器目录失败: %w", err)
	}

	compose := ComposeFile{
		Version: "3.8",
		Services: map[string]ComposeService{
			containerName: service,
		},
	}

	data, err := yaml.Marshal(&compose)
	if err != nil {
		return fmt.Errorf("序列化 compose 配置失败: %w", err)
	}

	header := "# Auto-generated by isrvd\n# Do not edit manually unless necessary\n\n"
	content := header + string(data)

	composePath := filepath.Join(containerDir, "docker-compose.yml")
	if err := os.WriteFile(composePath, []byte(content), 0644); err != nil {
		return fmt.Errorf("写入 compose 文件失败: %w", err)
	}

	return nil
}

// ReadComposeFile 读取 compose 配置文件
func ReadComposeFile(containerRoot, containerName string) (*ComposeFile, error) {
	if containerRoot == "" || containerName == "" {
		return nil, fmt.Errorf("容器目录未配置")
	}

	composePath := filepath.Join(containerRoot, containerName, "docker-compose.yml")
	data, err := os.ReadFile(composePath)
	if err != nil {
		return nil, fmt.Errorf("读取 compose 文件失败: %w", err)
	}

	var compose ComposeFile
	if err := yaml.Unmarshal(data, &compose); err != nil {
		return nil, fmt.Errorf("解析 compose 文件失败: %w", err)
	}

	return &compose, nil
}

// UpdateComposeFile 更新 compose 配置文件
func UpdateComposeFile(containerRoot, containerName string, service ComposeService) error {
	if containerRoot == "" || containerName == "" {
		return fmt.Errorf("容器目录未配置")
	}

	containerDir := filepath.Join(containerRoot, containerName)
	if err := os.MkdirAll(containerDir, 0755); err != nil {
		return fmt.Errorf("创建容器目录失败: %w", err)
	}

	compose := ComposeFile{
		Version: "3.8",
		Services: map[string]ComposeService{
			containerName: service,
		},
	}

	data, err := yaml.Marshal(&compose)
	if err != nil {
		return fmt.Errorf("序列化 compose 配置失败: %w", err)
	}

	header := "# Auto-generated by isrvd\n# Do not edit manually unless necessary\n\n"
	content := header + string(data)

	composePath := filepath.Join(containerDir, "docker-compose.yml")
	if err := os.WriteFile(composePath, []byte(content), 0644); err != nil {
		return fmt.Errorf("写入 compose 文件失败: %w", err)
	}

	return nil
}

// ParsePortsToMap 解析端口列表为 map
func ParsePortsToMap(ports []string) map[string]string {
	result := make(map[string]string)
	for _, p := range ports {
		parts := strings.Split(p, ":")
		if len(parts) >= 2 {
			hostPort := parts[0]
			containerPort := parts[1]
			// 处理 IP:port:port 格式
			if strings.Contains(hostPort, ".") && len(parts) >= 3 {
				hostPort = parts[1]
				containerPort = parts[2]
			}
			containerPort = strings.Split(containerPort, "/")[0]
			result[hostPort] = containerPort
		}
	}
	return result
}

// ParseVolumesToList 解析卷列表
func ParseVolumesToList(volumes []string) []VolumeMapping {
	var result []VolumeMapping
	for _, v := range volumes {
		parts := strings.Split(v, ":")
		if len(parts) >= 2 {
			info := VolumeMapping{
				HostPath:      parts[0],
				ContainerPath: parts[1],
			}
			if len(parts) >= 3 && parts[2] == "ro" {
				info.ReadOnly = true
			}
			result = append(result, info)
		}
	}
	return result
}

// VolumeMapping 卷映射（与 model.VolumeMapping 保持一致）
type VolumeMapping struct {
	HostPath      string `json:"hostPath"`
	ContainerPath string `json:"containerPath"`
	ReadOnly      bool   `json:"readOnly"`
}

// VolumeInfo 卷信息
type VolumeInfo struct {
	HostPath      string `json:"hostPath"`
	ContainerPath string `json:"containerPath"`
	ReadOnly      bool   `json:"readOnly"`
}
