package docker

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	yaml "gopkg.in/yaml.v3"
)

// composeService 定义 docker-compose service 配置
type composeService struct {
	Image         string            `yaml:"image"`
	ContainerName string            `yaml:"container_name,omitempty"`
	Environment   []string          `yaml:"environment,omitempty"`
	Ports         []string          `yaml:"ports,omitempty"`
	Volumes       []string          `yaml:"volumes,omitempty"`
	NetworkMode   string            `yaml:"network_mode,omitempty"`
	Restart       string            `yaml:"restart,omitempty"`
	Command       string            `yaml:"command,omitempty"`
	Entrypoint    string            `yaml:"entrypoint,omitempty"`
	WorkingDir    string            `yaml:"working_dir,omitempty"`
	User          string            `yaml:"user,omitempty"`
	Hostname      string            `yaml:"hostname,omitempty"`
	Privileged    bool              `yaml:"privileged,omitempty"`
	CapAdd        []string          `yaml:"cap_add,omitempty"`
	CapDrop       []string          `yaml:"cap_drop,omitempty"`
	Deploy        *composeDeploy    `yaml:"deploy,omitempty"`
	Labels        map[string]string `yaml:"labels,omitempty"`
}

// composeDeploy 定义资源限制配置
type composeDeploy struct {
	Resources *composeResources `yaml:"resources,omitempty"`
}

// composeResources 定义资源配置
type composeResources struct {
	Limits *composeLimit `yaml:"limits,omitempty"`
}

// composeLimit 定义资源限制
type composeLimit struct {
	Cpus   string `yaml:"cpus,omitempty"`
	Memory string `yaml:"memory,omitempty"`
}

// composeFile 定义 docker-compose 文件结构
type composeFile struct {
	Version  string                    `yaml:"version"`
	Services map[string]composeService `yaml:"services"`
}

// createComposeFileOnDisk 创建 compose 配置文件
func createComposeFileOnDisk(containerRoot, containerName string, service composeService) error {
	if containerRoot == "" || containerName == "" {
		return nil
	}

	containerDir := filepath.Join(containerRoot, containerName)
	if err := os.MkdirAll(containerDir, 0755); err != nil {
		return fmt.Errorf("创建容器目录失败: %w", err)
	}

	compose := composeFile{
		Version: "3.8",
		Services: map[string]composeService{
			containerName: service,
		},
	}

	data, err := yaml.Marshal(&compose)
	if err != nil {
		return fmt.Errorf("序列化 compose 配置失败: %w", err)
	}

	header := "# Auto-generated by isrvd\n# Do not edit manually unless necessary\n\n"
	content := header + string(data)

	composePath := filepath.Join(containerDir, "docker-compose.yml")
	if err := os.WriteFile(composePath, []byte(content), 0644); err != nil {
		return fmt.Errorf("写入 compose 文件失败: %w", err)
	}

	return nil
}

// readComposeFileFromDisk 读取 compose 配置文件
func readComposeFileFromDisk(containerRoot, containerName string) (*composeFile, error) {
	if containerRoot == "" || containerName == "" {
		return nil, fmt.Errorf("容器目录未配置")
	}

	composePath := filepath.Join(containerRoot, containerName, "docker-compose.yml")
	data, err := os.ReadFile(composePath)
	if err != nil {
		return nil, fmt.Errorf("读取 compose 文件失败: %w", err)
	}

	var compose composeFile
	if err := yaml.Unmarshal(data, &compose); err != nil {
		return nil, fmt.Errorf("解析 compose 文件失败: %w", err)
	}

	return &compose, nil
}

// updateComposeFileOnDisk 更新 compose 配置文件
func updateComposeFileOnDisk(containerRoot, containerName string, service composeService) error {
	if containerRoot == "" || containerName == "" {
		return fmt.Errorf("容器目录未配置")
	}

	containerDir := filepath.Join(containerRoot, containerName)
	if err := os.MkdirAll(containerDir, 0755); err != nil {
		return fmt.Errorf("创建容器目录失败: %w", err)
	}

	compose := composeFile{
		Version: "3.8",
		Services: map[string]composeService{
			containerName: service,
		},
	}

	data, err := yaml.Marshal(&compose)
	if err != nil {
		return fmt.Errorf("序列化 compose 配置失败: %w", err)
	}

	header := "# Auto-generated by isrvd\n# Do not edit manually unless necessary\n\n"
	content := header + string(data)

	composePath := filepath.Join(containerDir, "docker-compose.yml")
	if err := os.WriteFile(composePath, []byte(content), 0644); err != nil {
		return fmt.Errorf("写入 compose 文件失败: %w", err)
	}

	return nil
}

// parsePortsToMap 解析端口列表为 map
func parsePortsToMap(ports []string) map[string]string {
	result := make(map[string]string)
	for _, p := range ports {
		parts := strings.Split(p, ":")
		if len(parts) >= 2 {
			hostPort := parts[0]
			containerPort := parts[1]
			if strings.Contains(hostPort, ".") && len(parts) >= 3 {
				hostPort = parts[1]
				containerPort = parts[2]
			}
			containerPort = strings.Split(containerPort, "/")[0]
			result[hostPort] = containerPort
		}
	}
	return result
}

// parseVolumesToList 解析卷列表
func parseVolumesToList(volumes []string) []VolumeMapping {
	var result []VolumeMapping
	for _, v := range volumes {
		parts := strings.Split(v, ":")
		if len(parts) >= 2 {
			info := VolumeMapping{
				HostPath:      parts[0],
				ContainerPath: parts[1],
			}
			if len(parts) >= 3 && parts[2] == "ro" {
				info.ReadOnly = true
			}
			result = append(result, info)
		}
	}
	return result
}
