export interface FaIcon {
    name: string
    label: string
    prefix?: 'fas' | 'fab'
}

// 从项目代码中提取的 Font Awesome 图标（适合用作导航链接图标）
export const FA_ICONS: FaIcon[] = [
    // ─── 通用 ───
    { name: 'fa-link',                  label: '链接' },
    { name: 'fa-globe',                 label: '地球' },
    { name: 'fa-house',                 label: '主页' },
    { name: 'fa-home',                  label: '首页' },
    { name: 'fa-bookmark',              label: '书签' },
    { name: 'fa-star',                  label: '收藏' },
    { name: 'fa-heart',                 label: '喜欢' },
    { name: 'fa-flag',                  label: '旗帜' },
    { name: 'fa-tag',                   label: '标签' },
    { name: 'fa-tags',                  label: '标签组' },
    { name: 'fa-bell',                  label: '通知' },
    { name: 'fa-envelope',              label: '邮件' },
    { name: 'fa-circle-info',           label: '信息' },
    { name: 'fa-circle-question',       label: '帮助' },
    { name: 'fa-magnifying-glass',      label: '搜索' },
    { name: 'fa-rocket',                label: '火箭' },
    { name: 'fa-bolt',                  label: '闪电' },
    { name: 'fa-crown',                 label: '皇冠' },
    { name: 'fa-wand-magic-sparkles',   label: '魔法' },
    // ─── 数据 & 图表 ───
    { name: 'fa-chart-line',            label: '折线图' },
    { name: 'fa-chart-bar',             label: '柱状图' },
    { name: 'fa-chart-pie',             label: '饼图' },
    { name: 'fa-chart-area',            label: '面积图' },
    { name: 'fa-gauge',                 label: '仪表盘' },
    { name: 'fa-gauge-high',            label: '仪表盘（高）' },
    { name: 'fa-table',                 label: '表格' },
    { name: 'fa-table-columns',         label: '列表' },
    { name: 'fa-list-ol',               label: '有序列表' },
    { name: 'fa-list-check',            label: '任务列表' },
    { name: 'fa-database',              label: '数据库' },
    // ─── 基础设施 ───
    { name: 'fa-server',                label: '服务器' },
    { name: 'fa-cloud',                 label: '云' },
    { name: 'fa-cloud-arrow-up',        label: '上传云' },
    { name: 'fa-cloud-arrow-down',      label: '下载云' },
    { name: 'fa-network-wired',         label: '网络' },
    { name: 'fa-sitemap',               label: '拓扑' },
    { name: 'fa-layer-group',           label: '层级' },
    { name: 'fa-microchip',             label: '芯片' },
    { name: 'fa-memory',                label: '内存' },
    { name: 'fa-hard-drive',            label: '磁盘' },
    { name: 'fa-temperature-half',      label: '温度' },
    { name: 'fa-warehouse',             label: '仓库' },
    { name: 'fa-circle-nodes',          label: '节点' },
    { name: 'fa-route',                 label: '路由' },
    { name: 'fa-ship',                  label: '容器船' },
    { name: 'fa-cube',                  label: '容器' },
    { name: 'fa-cubes',                 label: '容器组' },
    { name: 'fa-box',                   label: '包' },
    { name: 'fa-compact-disc',          label: '镜像' },
    // ─── 开发 & 运维 ───
    { name: 'fa-terminal',              label: '终端' },
    { name: 'fa-code',                  label: '代码' },
    { name: 'fa-code-branch',           label: '分支' },
    { name: 'fa-bug',                   label: 'Bug' },
    { name: 'fa-robot',                 label: '机器人' },
    { name: 'fa-gear',                  label: '设置' },
    { name: 'fa-gears',                 label: '配置' },
    { name: 'fa-cogs',                  label: '齿轮组' },
    { name: 'fa-wrench',                label: '扳手' },
    { name: 'fa-screwdriver-wrench',    label: '维护' },
    { name: 'fa-hammer',                label: '锤子' },
    { name: 'fa-plug',                  label: '插件' },
    { name: 'fa-puzzle-piece',          label: '扩展' },
    { name: 'fa-rotate',                label: '刷新' },
    { name: 'fa-arrows-rotate',         label: '同步' },
    { name: 'fa-play',                  label: '运行' },
    { name: 'fa-stop',                  label: '停止' },
    { name: 'fa-pause',                 label: '暂停' },
    { name: 'fa-power-off',             label: '关机' },
    { name: 'fa-fan',                   label: '风扇' },
    { name: 'fa-tasks',                 label: '任务' },
    { name: 'fa-store',                 label: '市场' },
    // ─── 安全 ───
    { name: 'fa-shield',                label: '安全' },
    { name: 'fa-shield-halved',         label: '防护' },
    { name: 'fa-key',                   label: '密钥' },
    { name: 'fa-lock',                  label: '锁定' },
    { name: 'fa-lock-open',             label: '解锁' },
    { name: 'fa-user-shield',           label: '用户安全' },
    { name: 'fa-certificate',           label: '证书' },
    // ─── 文件 & 文档 ───
    { name: 'fa-file',                  label: '文件' },
    { name: 'fa-file-code',             label: '代码文件' },
    { name: 'fa-file-lines',            label: '文本文件' },
    { name: 'fa-file-alt',              label: '文本' },
    { name: 'fa-file-import',           label: '导入文件' },
    { name: 'fa-file-circle-plus',      label: '新建文件' },
    { name: 'fa-file-zipper',           label: '压缩文件' },
    { name: 'fa-folder',                label: '文件夹' },
    { name: 'fa-folder-open',           label: '打开文件夹' },
    { name: 'fa-book',                  label: '文档' },
    { name: 'fa-book-open',             label: '手册' },
    { name: 'fa-newspaper',             label: '新闻' },
    { name: 'fa-clipboard',             label: '剪贴板' },
    { name: 'fa-note-sticky',           label: '便签' },
    { name: 'fa-download',              label: '下载' },
    { name: 'fa-upload',                label: '上传' },
    // ─── 用户 & 团队 ───
    { name: 'fa-user',                  label: '用户' },
    { name: 'fa-user-tie',              label: '管理员' },
    { name: 'fa-user-tag',              label: '用户标签' },
    { name: 'fa-users',                 label: '团队' },
    { name: 'fa-user-group',            label: '用户组' },
    { name: 'fa-address-card',          label: '名片' },
    // ─── 品牌（fab 前缀）───
    { name: 'fa-docker',    label: 'Docker',      prefix: 'fab' },
    { name: 'fa-github',    label: 'GitHub',      prefix: 'fab' },
    { name: 'fa-gitlab',    label: 'GitLab',      prefix: 'fab' },
    { name: 'fa-git-alt',   label: 'Git',         prefix: 'fab' },
    { name: 'fa-linux',     label: 'Linux',       prefix: 'fab' },
    { name: 'fa-python',    label: 'Python',      prefix: 'fab' },
    { name: 'fa-js',        label: 'JavaScript',  prefix: 'fab' },
    { name: 'fa-node-js',   label: 'Node.js',     prefix: 'fab' },
    { name: 'fa-react',     label: 'React',       prefix: 'fab' },
    { name: 'fa-vuejs',     label: 'Vue',         prefix: 'fab' },
    { name: 'fa-aws',       label: 'AWS',         prefix: 'fab' },
    { name: 'fa-google',    label: 'Google',      prefix: 'fab' },
    { name: 'fa-slack',     label: 'Slack',       prefix: 'fab' },
    { name: 'fa-confluence', label: 'Confluence', prefix: 'fab' },
    { name: 'fa-jira',      label: 'Jira',        prefix: 'fab' },
    { name: 'fa-jenkins',   label: 'Jenkins',     prefix: 'fab' },
    { name: 'fa-grafana',   label: 'Grafana',     prefix: 'fab' },
    { name: 'fa-prometheus', label: 'Prometheus', prefix: 'fab' },
    { name: 'fa-kubernetes', label: 'Kubernetes', prefix: 'fab' },
    { name: 'fa-markdown',  label: 'Markdown',    prefix: 'fab' },
    { name: 'fa-html5',     label: 'HTML5',       prefix: 'fab' },
    { name: 'fa-css3-alt',  label: 'CSS3',        prefix: 'fab' },
    { name: 'fa-php',       label: 'PHP',         prefix: 'fab' },
    { name: 'fa-java',      label: 'Java',        prefix: 'fab' },
]
