// Package compose 提供基于 compose-spec 官方规范的 compose 文件加载、变量插值、
// YAML 序列化以及与 pkgs/docker、pkgs/swarm 数据结构的双向转换能力。
//
// 本包是纯解析/转换层，不直接操作底层容器/网络/卷的 CRUD —
// 具体的部署、网络确保、镜像拉取等编排能力由上层 internal/service/compose 完成。
package compose

import (
	"bytes"
	"context"
	"fmt"
	"log/slog"
	"maps"
	"os"
	"path/filepath"
	"strings"

	"github.com/compose-spec/compose-go/v2/dotenv"
	"github.com/compose-spec/compose-go/v2/loader"
	"github.com/compose-spec/compose-go/v2/types"
	"github.com/goccy/go-yaml"
)

// composeFileCandidates 常见的 compose 文件名（按优先级）
var composeFileCandidates = []string{
	"compose.yaml",
	"compose.yml",
	"docker-compose.yaml",
	"docker-compose.yml",
}

// ProjectToYAML 使用 compose-go 官方序列化器输出 YAML（带文件头）
func ProjectToYAML(project *types.Project) ([]byte, error) {
	if project == nil {
		return nil, fmt.Errorf("project 为空")
	}
	data, err := project.MarshalYAML()
	if err != nil {
		return nil, fmt.Errorf("序列化 compose 失败: %w", err)
	}
	return append([]byte("# Auto-generated by iSrvd\n\n"), data...), nil
}

// LoadOptions 加载配置
type LoadOptions struct {
	WorkingDir  string            // compose 文件所在目录（用于解析相对路径和 .env）
	ConfigFiles []string          // 指定要加载的 compose 文件绝对路径；为空则在 WorkingDir 下自动查找
	ProjectName string            // 项目名（影响生成的网络/容器默认前缀）
	Environment map[string]string // 额外的环境变量（并入进程环境，优先级高于 .env）
}

// LoadProject 使用 compose-go 官方加载器解析 compose 文件，
// 自动处理 .env、变量插值、schema 校验等一致性检查
func LoadProject(ctx context.Context, opts LoadOptions) (*types.Project, error) {
	if opts.WorkingDir == "" {
		return nil, fmt.Errorf("缺少工作目录")
	}

	configFiles, err := resolveConfigFiles(opts.WorkingDir, opts.ConfigFiles)
	if err != nil {
		return nil, err
	}
	files, err := readConfigFiles(configFiles)
	if err != nil {
		return nil, err
	}

	projectName := opts.ProjectName
	if projectName == "" {
		projectName = filepath.Base(opts.WorkingDir)
	}

	env, err := projectEnvironmentWithEnvFile(ctx, opts.Environment, nil, opts.WorkingDir)
	if err != nil {
		return nil, err
	}

	return loadProject(ctx, types.ConfigDetails{
		WorkingDir:  opts.WorkingDir,
		ConfigFiles: files,
		Environment: env,
	}, projectName, true, true)
}

// LoadProjectFromContent 从 yaml 文本加载 compose 项目（不解析相对路径）。
func LoadProjectFromContent(ctx context.Context, content string, projectName string) (*types.Project, error) {
	return LoadProjectFromContentInDir(ctx, content, ".", projectName, nil)
}

// LoadProjectFromContentInDir 从 yaml 文本加载 compose 项目，并以 workingDir 解析相对路径。
// envContent 为 nil 时仅读 workingDir/.env；非 nil 时在磁盘 .env 之上叠加。
func LoadProjectFromContentInDir(ctx context.Context, content, workingDir, projectName string, envContent *string) (*types.Project, error) {
	if workingDir == "" {
		workingDir = "."
	}
	return loadProjectContent(ctx, content, workingDir, projectName, true, envContent)
}

// loadProjectContent 从 yaml 文本加载 compose 项目，并合并指定的 .env 内容到插值环境。
// envContent 为 nil 时仅读 workingDir/.env；非 nil 时在磁盘 .env 之上叠加。
func loadProjectContent(ctx context.Context, content, workingDir, projectName string, resolvePaths bool, envContent *string) (*types.Project, error) {
	if content == "" {
		return nil, fmt.Errorf("compose 内容为空")
	}

	env, err := projectEnvironmentWithEnvFile(ctx, nil, envContent, workingDir)
	if err != nil {
		return nil, err
	}

	details := types.ConfigDetails{
		WorkingDir: workingDir,
		ConfigFiles: []types.ConfigFile{
			{
				Filename: "compose.yml",
				Content:  []byte(content),
			},
		},
		Environment: env,
	}

	return loadProject(ctx, details, projectName, resolvePaths, projectName != "")
}

func loadProject(ctx context.Context, details types.ConfigDetails, projectName string, resolvePaths bool, setProjectName bool) (*types.Project, error) {
	return loadProjectWithOptions(ctx, details, projectName, resolvePaths, setProjectName, nil)
}

func loadProjectWithOptions(ctx context.Context, details types.ConfigDetails, projectName string, resolvePaths bool, setProjectName bool, configure func(*loader.Options)) (*types.Project, error) {
	projectName = loader.NormalizeProjectName(projectName)
	project, err := loader.LoadWithContext(ctx, details, func(o *loader.Options) {
		if setProjectName && projectName != "" {
			o.SetProjectName(projectName, true)
		}
		o.SkipConsistencyCheck = false
		o.SkipValidation = false
		o.ResolvePaths = resolvePaths
		if configure != nil {
			configure(o)
		}
	})
	if err != nil {
		return nil, fmt.Errorf("加载 compose 失败: %w", err)
	}
	return project, nil
}

// ProjectValidateWithoutEnvFiles 在不读取 services.env_file 的前提下校验 Compose 结构，
// 返回解析结果供调用方复用（如项目名，已插值+规范化；未声明 name 时用内容短哈希兜底）。
// 用于部署落盘前预检；env_file 仅在文件就位后的正式加载阶段解析。
func ProjectValidateWithoutEnvFiles(ctx context.Context, content string, envContent *string) (*types.Project, error) {
	if content == "" {
		return nil, fmt.Errorf("compose 内容为空")
	}
	env, err := projectEnvironmentWithEnvFile(ctx, nil, envContent, "")
	if err != nil {
		return nil, err
	}
	details := types.ConfigDetails{
		WorkingDir: ".",
		ConfigFiles: []types.ConfigFile{{
			Filename: "compose.yml",
			Content:  []byte(content),
		}},
		Environment: env,
	}
	skipEnvFiles := func(o *loader.Options) {
		o.SkipResolveEnvironment = true
	}

	project, err := loadProjectWithOptions(ctx, details, "", false, false, skipEnvFiles)
	if err == nil {
		return project, nil
	}

	// 首次失败可能仅因未声明顶层 name，此时用内容短哈希兜底。
	// 但若声明了 name 却解析为空，说明插值变量未提供，必须报错而非静默改名。
	if declaresProjectName(content) {
		return nil, err
	}
	project, hashErr := loadProjectWithOptions(ctx, details, ShortHash(content), false, true, skipEnvFiles)
	if hashErr != nil {
		return nil, err
	}
	return project, nil
}

func projectEnvironment(extra map[string]string) map[string]string {
	env := make(map[string]string)
	for _, e := range os.Environ() {
		for i := 0; i < len(e); i++ {
			if e[i] == '=' {
				env[e[:i]] = e[i+1:]
				break
			}
		}
	}
	maps.Copy(env, extra)
	return env
}

// projectEnvironmentWithEnvFile 构建 ${VAR} 插值环境。
func projectEnvironmentWithEnvFile(ctx context.Context, extra map[string]string, envContent *string, workingDir string) (map[string]string, error) {
	env := make(map[string]string)

	if workingDir != "" {
		envFilePath := filepath.Join(workingDir, EnvFileName)
		if data, err := os.ReadFile(envFilePath); err == nil {
			fileEnv, perr := parseEnvContent(string(data))
			if perr != nil {
				return nil, fmt.Errorf("解析 %s 失败: %w", envFilePath, perr)
			}
			maps.Copy(env, fileEnv)
		} else if !os.IsNotExist(err) {
			slog.DebugContext(ctx, "read project .env failed", "path", envFilePath, "error", err)
		}
	}

	if envContent != nil && strings.TrimSpace(*envContent) != "" {
		fileEnv, err := parseEnvContent(*envContent)
		if err != nil {
			return nil, fmt.Errorf("解析 .env 内容失败: %w", err)
		}
		maps.Copy(env, fileEnv)
	}

	maps.Copy(env, projectEnvironment(extra))

	return env, nil
}

// parseEnvContent 解析 KEY=VALUE 形式的 .env 文本。
func parseEnvContent(content string) (map[string]string, error) {
	return dotenv.Parse(bytes.NewReader([]byte(content)))
}
func resolveConfigFiles(workingDir string, configFiles []string) ([]string, error) {
	if len(configFiles) > 0 {
		return configFiles, nil
	}
	found, err := locateComposeFile(workingDir)
	if err != nil {
		return nil, err
	}
	return []string{found}, nil
}

func readConfigFiles(paths []string) ([]types.ConfigFile, error) {
	files := make([]types.ConfigFile, 0, len(paths))
	for _, p := range paths {
		data, err := os.ReadFile(p)
		if err != nil {
			return nil, fmt.Errorf("读取 compose 文件失败: %w", err)
		}
		files = append(files, types.ConfigFile{Filename: p, Content: data})
	}
	return files, nil
}

// locateComposeFile 在 dir 下查找 compose 文件，根目录找不到时尝试一级子目录。
func locateComposeFile(dir string) (string, error) {
	if p, ok := findComposeFile(dir); ok {
		return p, nil
	}

	entries, err := os.ReadDir(dir)
	if err != nil {
		return "", fmt.Errorf("读取目录失败: %w", err)
	}
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		if p, ok := findComposeFile(filepath.Join(dir, e.Name())); ok {
			return p, nil
		}
	}
	return "", fmt.Errorf("目录中未找到 compose 文件")
}

func findComposeFile(dir string) (string, bool) {
	for _, name := range composeFileCandidates {
		p := filepath.Join(dir, name)
		if st, err := os.Stat(p); err == nil && !st.IsDir() {
			return p, true
		}
	}
	return "", false
}

// ─── 辅助函数 ───

// declaresProjectName 判断 compose 文本是否声明了顶层 name 键。
func declaresProjectName(content string) bool {
	var doc struct {
		Name *string `yaml:"name"`
	}
	if err := yaml.Unmarshal([]byte(content), &doc); err != nil {
		return false
	}
	return doc.Name != nil
}
