// Package compose snapshot 提供「容器请求 → compose 项目」的单向转换和 YAML 序列化。
package compose

import (
	"fmt"
	"strconv"
	"strings"

	"github.com/compose-spec/compose-go/v2/types"
	dockertypes "github.com/docker/docker/api/types"

	"isrvd/pkgs/docker"
)

// ProjectFromCreateRequest 将 ContainerCreateRequest 转为单服务 compose Project
func ProjectFromCreateRequest(req docker.ContainerCreateRequest) (*types.Project, error) {
	if req.Name == "" || req.Image == "" {
		return nil, fmt.Errorf("name 或 image 为空")
	}

	svc := types.ServiceConfig{
		Name:          req.Name,
		Image:         req.Image,
		ContainerName: req.Name,
		Command:       types.ShellCommand(req.Cmd),
		Environment:   sliceToEnv(req.Env),
		NetworkMode:   req.Network,
		WorkingDir:    req.Workdir,
		User:          req.User,
		Hostname:      req.Hostname,
		Privileged:    req.Privileged,
		CapAdd:        req.CapAdd,
		CapDrop:       req.CapDrop,
		Restart:       defaultString(req.Restart, "always"),
	}

	for host, container := range req.Ports {
		svc.Ports = append(svc.Ports, types.ServicePortConfig{
			Target:    parsePort(container),
			Published: host,
			Protocol:  "tcp",
			Mode:      "ingress",
		})
	}

	for _, v := range req.Volumes {
		svc.Volumes = append(svc.Volumes, types.ServiceVolumeConfig{
			Type:     types.VolumeTypeBind,
			Source:   v.HostPath,
			Target:   v.ContainerPath,
			ReadOnly: v.ReadOnly,
		})
	}

	if req.Memory > 0 || req.Cpus > 0 {
		svc.Deploy = &types.DeployConfig{
			Resources: types.Resources{Limits: &types.Resource{
				MemoryBytes: types.UnitBytes(req.Memory * 1024 * 1024),
				NanoCPUs:    types.NanoCPUs(req.Cpus),
			}},
		}
	}

	return &types.Project{
		Name:     req.Name,
		Services: types.Services{req.Name: svc},
	}, nil
}

// ProjectFromInspect 将 docker inspect 结果反推为单服务 compose Project（用于运行态创建快照）
func ProjectFromInspect(info dockertypes.ContainerJSON) (*types.Project, error) {
	if info.Config == nil || info.HostConfig == nil {
		return nil, fmt.Errorf("容器 inspect 数据不完整")
	}
	name := strings.TrimPrefix(info.Name, "/")
	if name == "" {
		name = info.ID
	}

	svc := types.ServiceConfig{
		Name:          name,
		Image:         info.Config.Image,
		ContainerName: name,
		Command:       types.ShellCommand(info.Config.Cmd),
		Environment:   sliceToEnv(info.Config.Env),
		WorkingDir:    info.Config.WorkingDir,
		User:          info.Config.User,
		Hostname:      info.Config.Hostname,
		Privileged:    info.HostConfig.Privileged,
		CapAdd:        []string(info.HostConfig.CapAdd),
		CapDrop:       []string(info.HostConfig.CapDrop),
		Restart:       defaultString(string(info.HostConfig.RestartPolicy.Name), "always"),
		NetworkMode:   string(info.HostConfig.NetworkMode),
	}

	// 端口映射：HostConfig.PortBindings (容器端口 → 宿主绑定列表)
	for containerPort, bindings := range info.HostConfig.PortBindings {
		target := parsePort(containerPort.Port())
		proto := containerPort.Proto()
		if proto == "" {
			proto = "tcp"
		}
		if len(bindings) == 0 {
			svc.Ports = append(svc.Ports, types.ServicePortConfig{
				Target:   target,
				Protocol: proto,
				Mode:     "ingress",
			})
			continue
		}
		for _, b := range bindings {
			svc.Ports = append(svc.Ports, types.ServicePortConfig{
				Target:    target,
				Published: b.HostPort,
				Protocol:  proto,
				Mode:      "ingress",
			})
		}
	}

	// 挂载：优先用 Mounts（结构化），其次 HostConfig.Binds（字符串回退）
	for _, m := range info.Mounts {
		if m.Destination == "" {
			continue
		}
		svc.Volumes = append(svc.Volumes, types.ServiceVolumeConfig{
			Type:     string(m.Type),
			Source:   m.Source,
			Target:   m.Destination,
			ReadOnly: !m.RW,
		})
	}
	if len(svc.Volumes) == 0 {
		for _, bind := range info.HostConfig.Binds {
			parts := strings.SplitN(bind, ":", 3)
			if len(parts) < 2 {
				continue
			}
			vol := types.ServiceVolumeConfig{
				Type:   types.VolumeTypeBind,
				Source: parts[0],
				Target: parts[1],
			}
			if len(parts) == 3 && strings.Contains(parts[2], "ro") {
				vol.ReadOnly = true
			}
			svc.Volumes = append(svc.Volumes, vol)
		}
	}

	// 资源限制
	if info.HostConfig.Memory > 0 || info.HostConfig.NanoCPUs > 0 {
		svc.Deploy = &types.DeployConfig{
			Resources: types.Resources{Limits: &types.Resource{
				MemoryBytes: types.UnitBytes(info.HostConfig.Memory),
				NanoCPUs:    types.NanoCPUs(float64(info.HostConfig.NanoCPUs) / 1e9),
			}},
		}
	}

	return &types.Project{
		Name:     name,
		Services: types.Services{name: svc},
	}, nil
}

// ProjectToYAML 使用 compose-go 官方序列化器输出 YAML（带文件头）
func ProjectToYAML(project *types.Project) ([]byte, error) {
	if project == nil {
		return nil, fmt.Errorf("project 为空")
	}
	data, err := project.MarshalYAML()
	if err != nil {
		return nil, fmt.Errorf("序列化 compose 失败: %w", err)
	}
	return append([]byte("# Auto-generated by isrvd\n\n"), data...), nil
}

// sliceToEnv 将 KEY=VALUE 列表转成 MappingWithEquals
func sliceToEnv(env []string) types.MappingWithEquals {
	if len(env) == 0 {
		return nil
	}
	result := make(types.MappingWithEquals, len(env))
	for _, e := range env {
		if e == "" {
			continue
		}
		if idx := strings.Index(e, "="); idx > 0 {
			v := e[idx+1:]
			result[e[:idx]] = &v
		} else {
			result[e] = nil
		}
	}
	return result
}

// parsePort 解析 "8080" 或 "8080/tcp" 为端口号
func parsePort(s string) uint32 {
	if i := strings.Index(s, "/"); i >= 0 {
		s = s[:i]
	}
	n, _ := strconv.Atoi(s)
	if n < 0 {
		return 0
	}
	return uint32(n)
}

func defaultString(v, def string) string {
	if v == "" {
		return def
	}
	return v
}
