package docker

import (
	"archive/tar"
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/docker/docker/api/types"
	yaml "gopkg.in/yaml.v3"
)

// isWildcardIP 判断 IP 是否为通配地址（0.0.0.0 或 ::）
func isWildcardIP(ip string) bool {
	return ip == "" || ip == "0.0.0.0" || ip == "::"
}

// formatPorts 格式化端口列表：IPv4 优先、去重、通配地址省略 IP
//
// 算法：单次遍历，用 seen map 记录已输出的 key；
// IPv6 条目若已有对应 IPv4 条目则跳过，否则正常输出。
func formatPorts(ports []types.Port) []string {
	seen := make(map[string]bool, len(ports))
	result := make([]string, 0, len(ports))

	for _, p := range ports {
		var entry, key string
		isIPv6 := strings.Contains(p.IP, ":")

		if p.PublicPort > 0 {
			key = fmt.Sprintf("%d:%d/%s", p.PublicPort, p.PrivatePort, p.Type)
			// IPv6 且已有 IPv4 同 key，跳过
			if isIPv6 && seen[key] {
				continue
			}
			if isWildcardIP(p.IP) {
				entry = fmt.Sprintf("%d:%d/%s", p.PublicPort, p.PrivatePort, p.Type)
			} else {
				entry = fmt.Sprintf("%s:%d:%d/%s", p.IP, p.PublicPort, p.PrivatePort, p.Type)
			}
		} else {
			key = fmt.Sprintf("%d/%s", p.PrivatePort, p.Type)
			entry = key
		}

		if !seen[key] {
			seen[key] = true
			result = append(result, entry)
		}
	}
	return result
}

// buildDockerfileTar 构建 Dockerfile 的 tar 包
func buildDockerfileTar(dockerfile string) (*bytes.Buffer, error) {
	tarBuf := new(bytes.Buffer)
	tw := tar.NewWriter(tarBuf)
	hdr := &tar.Header{
		Name: "Dockerfile",
		Mode: 0644,
		Size: int64(len(dockerfile)),
	}
	if err := tw.WriteHeader(hdr); err != nil {
		return nil, err
	}
	if _, err := tw.Write([]byte(dockerfile)); err != nil {
		return nil, err
	}
	tw.Close()
	return tarBuf, nil
}

// createComposeFileOnDisk 创建 compose 配置文件
func createComposeFileOnDisk(containerRoot, containerName string, service composeService) error {
	if containerRoot == "" || containerName == "" {
		return nil
	}

	containerDir := filepath.Join(containerRoot, containerName)
	if err := os.MkdirAll(containerDir, 0755); err != nil {
		return fmt.Errorf("创建容器目录失败: %w", err)
	}

	compose := composeFile{
		Version: "3.8",
		Services: map[string]composeService{
			containerName: service,
		},
	}

	data, err := yaml.Marshal(&compose)
	if err != nil {
		return fmt.Errorf("序列化 compose 配置失败: %w", err)
	}

	header := "# Auto-generated by isrvd\n# Do not edit manually unless necessary\n\n"
	content := header + string(data)

	composePath := filepath.Join(containerDir, "docker-compose.yml")
	if err := os.WriteFile(composePath, []byte(content), 0644); err != nil {
		return fmt.Errorf("写入 compose 文件失败: %w", err)
	}

	return nil
}

// readComposeFileFromDisk 读取 compose 配置文件
func readComposeFileFromDisk(containerRoot, containerName string) (*composeFile, error) {
	if containerRoot == "" || containerName == "" {
		return nil, fmt.Errorf("容器目录未配置")
	}

	composePath := filepath.Join(containerRoot, containerName, "docker-compose.yml")
	data, err := os.ReadFile(composePath)
	if err != nil {
		return nil, fmt.Errorf("读取 compose 文件失败: %w", err)
	}

	var compose composeFile
	if err := yaml.Unmarshal(data, &compose); err != nil {
		return nil, fmt.Errorf("解析 compose 文件失败: %w", err)
	}

	return &compose, nil
}

// parsePortsToMap 解析端口列表为 map
func parsePortsToMap(ports []string) map[string]string {
	result := make(map[string]string)
	for _, p := range ports {
		parts := strings.Split(p, ":")
		if len(parts) >= 2 {
			hostPort := parts[0]
			containerPort := parts[1]
			if strings.Contains(hostPort, ".") && len(parts) >= 3 {
				hostPort = parts[1]
				containerPort = parts[2]
			}
			containerPort = strings.Split(containerPort, "/")[0]
			result[hostPort] = containerPort
		}
	}
	return result
}

// parseVolumesToList 解析卷列表
func parseVolumesToList(volumes []string) []VolumeMapping {
	var result []VolumeMapping
	for _, v := range volumes {
		parts := strings.Split(v, ":")
		if len(parts) >= 2 {
			info := VolumeMapping{
				HostPath:      parts[0],
				ContainerPath: parts[1],
			}
			if len(parts) >= 3 && parts[2] == "ro" {
				info.ReadOnly = true
			}
			result = append(result, info)
		}
	}
	return result
}

// ParseDockerLogs 解析 Docker multiplexed stream 格式的日志数据
// 移除每帧前 8 字节的头部，返回纯文本行列表
func ParseDockerLogs(data []byte) []string {
	var logs []string
	for i := 0; i < len(data); {
		if i+8 > len(data) {
			break
		}
		size := int(data[i+4])<<24 | int(data[i+5])<<16 | int(data[i+6])<<8 | int(data[i+7])
		i += 8
		if i+size > len(data) || size <= 0 {
			break
		}
		logs = append(logs, string(data[i:i+size]))
		i += size
	}
	return logs
}

// registryHost 从仓库 URL 中提取 host 部分（去掉协议前缀和路径），用于拼接镜像引用
// 例如：https://csighub.tencentyun.com -> csighub.tencentyun.com
func registryHost(registryURL string) string {
	host := strings.TrimPrefix(registryURL, "https://")
	host = strings.TrimPrefix(host, "http://")
	if idx := strings.Index(host, "/"); idx >= 0 {
		host = host[:idx]
	}
	return host
}

// formatUnixTime 将 Unix 时间戳格式化为 RFC3339 字符串
func formatUnixTime(ts int64) string {
	return time.Unix(ts, 0).UTC().Format(time.RFC3339)
}
